services:
  plataforma-electoral-milei:
    image: "jemanuelp/plataforma-electoral-milei:latest"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      restart_policy:
        condition: on-failure
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - 31018:${API_PORT}
    networks:
      - whatsapp

networks:
  whatsapp:
    external: true